//! Typed `zbus` proxies for the `NetworkManager` D-Bus API. Generated by
//! the `#[proxy]` macro at compile time, so method names and signatures
//! are checked against the declared interface signature.
//!
//! Reference: <https://networkmanager.dev/docs/api/latest/spec.html>.

use std::collections::HashMap;

use zbus::proxy;
use zbus::zvariant::{ObjectPath, OwnedObjectPath, OwnedValue, Value};

/// `org.freedesktop.NetworkManager` — root NM service.
#[proxy(
    interface = "org.freedesktop.NetworkManager",
    default_service = "org.freedesktop.NetworkManager",
    default_path = "/org/freedesktop/NetworkManager"
)]
pub trait NetworkManager {
    /// Enumerate every NM-managed device (Wi-Fi, Ethernet, etc.).
    fn get_all_devices(&self) -> zbus::Result<Vec<OwnedObjectPath>>;

    /// Activate an existing connection profile on a device.
    fn activate_connection(
        &self,
        connection: &ObjectPath<'_>,
        device: &ObjectPath<'_>,
        specific_object: &ObjectPath<'_>,
    ) -> zbus::Result<OwnedObjectPath>;

    /// Add a new connection profile and immediately activate it.
    /// Returns `(connection_path, active_connection_path)`.
    fn add_and_activate_connection(
        &self,
        connection: HashMap<String, HashMap<String, OwnedValue>>,
        device: &ObjectPath<'_>,
        specific_object: &ObjectPath<'_>,
    ) -> zbus::Result<(OwnedObjectPath, OwnedObjectPath)>;

    /// Tear down an active connection.
    fn deactivate_connection(&self, active_connection: &ObjectPath<'_>) -> zbus::Result<()>;

    #[zbus(property)]
    fn active_connections(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
}

/// `org.freedesktop.NetworkManager.Settings`.
#[proxy(
    interface = "org.freedesktop.NetworkManager.Settings",
    default_service = "org.freedesktop.NetworkManager",
    default_path = "/org/freedesktop/NetworkManager/Settings"
)]
pub trait Settings {
    /// Enumerate every saved connection profile.
    fn list_connections(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
}

/// `org.freedesktop.NetworkManager.Settings.Connection` — per-saved-profile.
#[proxy(
    interface = "org.freedesktop.NetworkManager.Settings.Connection",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait SettingsConnection {
    /// Read the full settings dictionary for this saved profile.
    fn get_settings(&self) -> zbus::Result<HashMap<String, HashMap<String, OwnedValue>>>;

    /// Delete the saved profile.
    fn delete(&self) -> zbus::Result<()>;
}

/// `org.freedesktop.NetworkManager.Device` — per-device base interface.
#[proxy(
    interface = "org.freedesktop.NetworkManager.Device",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Device {
    #[zbus(property)]
    fn device_type(&self) -> zbus::Result<u32>;

    /// Kernel interface name (`wlp3s0`, `wlan0`, etc.).
    #[zbus(property, name = "Interface")]
    fn interface(&self) -> zbus::Result<String>;

    /// Path of the currently-active connection on this device, or `"/"` when
    /// the device is unmanaged / disconnected.
    #[zbus(property)]
    fn active_connection(&self) -> zbus::Result<OwnedObjectPath>;
}

/// `org.freedesktop.NetworkManager.Device.Wireless` — Wi-Fi-specific.
#[proxy(
    interface = "org.freedesktop.NetworkManager.Device.Wireless",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait WirelessDevice {
    /// Kick off a fresh AP scan. Returns immediately; results stream into
    /// the `AccessPoints` property over the next ~1-3 seconds.
    fn request_scan(&self, options: HashMap<&str, Value<'_>>) -> zbus::Result<()>;

    #[zbus(property)]
    fn access_points(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
}

/// `org.freedesktop.NetworkManager.AccessPoint`.
#[proxy(
    interface = "org.freedesktop.NetworkManager.AccessPoint",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait AccessPoint {
    /// Raw SSID octets (NM does NOT validate UTF-8 here).
    #[zbus(property)]
    fn ssid(&self) -> zbus::Result<Vec<u8>>;

    /// 0..=100 normalized signal strength.
    #[zbus(property)]
    fn strength(&self) -> zbus::Result<u8>;

    /// Operating frequency in MHz.
    #[zbus(property)]
    fn frequency(&self) -> zbus::Result<u32>;

    /// BSSID, formatted as `xx:xx:xx:xx:xx:xx`.
    #[zbus(property)]
    fn hw_address(&self) -> zbus::Result<String>;

    /// `NM80211ApFlags` bitfield. Bit `0x1` = privacy (encrypted); higher
    /// bits encode WPS support.
    #[zbus(property)]
    fn flags(&self) -> zbus::Result<u32>;

    /// `NM80211ApSecurityFlags` bitfield encoding WPA1 / 802.11i
    /// key-management + cipher capabilities.
    #[zbus(property)]
    fn wpa_flags(&self) -> zbus::Result<u32>;

    /// `NM80211ApSecurityFlags` bitfield encoding RSN (WPA2/WPA3/OWE)
    /// key-management + cipher capabilities.
    #[zbus(property)]
    fn rsn_flags(&self) -> zbus::Result<u32>;
}

/// `org.freedesktop.NetworkManager.Connection.Active` — runtime state of
/// an in-flight or established connection.
#[proxy(
    interface = "org.freedesktop.NetworkManager.Connection.Active",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait ActiveConnection {
    /// `NMActiveConnectionState`: 0=Unknown, 1=Activating, 2=Activated,
    /// 3=Deactivating, 4=Deactivated.
    #[zbus(property)]
    fn state(&self) -> zbus::Result<u32>;

    #[zbus(property)]
    fn id(&self) -> zbus::Result<String>;

    /// For Wi-Fi connections this is the matching `AccessPoint` object path.
    #[zbus(property)]
    fn specific_object(&self) -> zbus::Result<OwnedObjectPath>;

    /// Devices this connection is bound to. For Wi-Fi this is a single
    /// `Device` path; we use it to filter actives by adapter.
    #[zbus(property)]
    fn devices(&self) -> zbus::Result<Vec<OwnedObjectPath>>;

    /// Fired on every state change. `(state, reason)` —
    /// reason is an `NMActiveConnectionStateReason`.
    #[zbus(signal, name = "StateChanged")]
    fn nm_state_changed(&self, state: u32, reason: u32) -> zbus::Result<()>;
}
